#!/bin/sh

usage="$(basename "$0") [OPTION]... [FILE]...
Batch converts .wdf files to .txt format, then stores all files in a single output directory
Wrapper around wdf-export utility from renishawWiRE
arguments:
	-h
		show this help message and exit
	-f
		filters out files that do not end in .wdf
	-d DIR
		changes the destination output directory to DIR

Author: Justin He"
 
# Parse arguments
filter=false
dir=""
while getopts "fhd:" opt; do
	case $opt in
		f)
			filter=true
			;;
		h)
			echo "$usage"
			exit 0
			;;
		d)
			dir="$OPTARG"
			;;
		\?)
			exit 1
			;;
	esac 
done
shift "$((OPTIND-1))"


# If no files provided, exit
if [ $# -eq 0 ];
then
	echo "No files provided"
	exit 1
fi

# Find first valid directory name if dir not specified
if [ "$dir" = "" ];
then
	LSOUT="$(ls -ld * | grep -E "wdfout[0-9]+")"
	n=0
	while [ $(echo $LSOUT | grep "wdfout$n" | wc -l) -gt 0 ]
	do
		((n++))
	done

	dir="./wdfout$n"
fi
mkdir $dir

# Parse files and convert each one from wdf to txt
# TODO: Determine whether to stop and delete at invalid file or continue parsing
echo "Converting..."
i=0
for file in "$@"
do
	if [ "$filter" = false ] || [ "$( echo $file | grep ".wdf$" | wc -l )" -gt 0 ];
	then
		((i++))
		echo -e "$i\t$file"
		FILENAME="$(echo $file | sed -n "s/^\(.*\)\.wdf$/\1/p").txt"
		WDFOUT="$(wdf-export -f '.txt' -p '%.6f' -o "$dir/$FILENAME" $file 2>&1 >/dev/null)" 
		if [ $? -ne 0 ];
		then
			((i--))
			rm -r $dir
			echo "$WDFOUT"
			exit 1
		fi
	fi
	
done 

echo "Converted $i files."
exit 0
